print("Data Structure and Algorithm using Python")
print("1: Arrays")
print("2: numpy Array")
print("3: List")
print("4: Dict")
print("5: Sets")
print("6: Tuple")
print("7: Stack")
print("8: Linked List")
print("9: Queue")
print("10: Circular queue")
print("Coming SOon")
